### ISSUE TITLE
Handle new hybrid taxon names 

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#472] opened 2024-02-01 11:20 UTC
**Describe the bug**
Due to the name being three or more string tokens - the rank is of hybrids will be incorrectly assigned.  

**To Reproduce**
1. create a Digi app record with a new hybrid name
2. save the record and check the SQLite DB specimen table

**Expected behavior**
Either:
The app should recognize hybrid names and treat them as such: Rank assigned should be species.
Or:
Post processing GREL script should be updated to handle novel hybrid names.

**Please complete the following information:**
 - [Mass Digitization App version 1.1.24](https://github.com/NHMDenmark/Mass-Digitizer/releases/tag/v1.1.24)

**Comment by FedorSteeman** [comment] 2024-02-07 15:45
Duplicate of #346

**Closed by FedorSteeman** 2024-02-07 15:45 UTC
Labels: frontend, specimen data entry, persistence, post-processing, bug
