### ISSUE TITLE
Can't create new taxa without author in DigiApp v. 1.1.24 if that taxon already exists with an author 

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Mass-Digitizer#466] opened 2024-01-12 14:31 UTC
**Describe the bug**

When entering a taxon into the DigiApp, the Author of that taxon is not always given on the specimen label, e.g. it is only called "Allium scorodoprasum", but the DigiApp only suggests that taxon with an Author: "Allium scorodoprasum L." When I try to create a new taxon without the "L." it always automatically autocompletes it back again, I cannot unselect it in the dropdown menu. There used to be a workaround for this (add two spaces and delete them again later I think), but this doesn't seem to work anymore. This is only a problem in cases where the taxon name without author isn't already imported yet.

**To Reproduce**
In DigiApp NHMD Vascular Plants, go to taxonomic name and try to enter only "Allium scorodoprasum". It doesn't work, it always autocompletes it to "Allium scorodoprasum L.".

**Expected behavior**
There should be a way to newly create taxon names of which a longer version already exists.

**Screenshots**
![GitHub Issue](https://github.com/NHMDenmark/Mass-Digitizer/assets/144137243/09e8263d-72b7-4528-98cc-46cf671197d7)

**Please complete the following information:**
 - version: 1.1.24, encountered during testing before release

**Comment by bhsi-snm** [comment] 2024-01-12 14:45
@FedorSteeman, there might be cases where we need this, can you check it out

**Comment by bhsi-snm** [comment] 2024-01-12 14:59
@FedorSteeman might be worth looking into @RebekkaML confirmed that closing the autosuggest leaves the taxa field empty, so this might be a problem.

**Comment by FedorSteeman** [comment] 2024-01-15 09:09
I see. Good this was caught.

**Comment by PipBrewer** [comment] 2024-01-16 14:37
Can confirm that it is not possible to add name if it is part of a existing one (e.g., if the author is not stated in association with the taxon name). This is captured in #257. If there is no easy way of doing this, perhaps we could add a character to all new names.

**Comment by FedorSteeman** [comment] 2024-02-01 11:53
I can see three ways of solving this: 
1. For each taxon name, add entries without author names to the taxon spine 
2. Avoid selection of top result in autosuggest box by pressing "Escape"
3. In cases where a choice is forced, the digitizer could add an asterisk to escape this situation 

I do not recommend 1, because we actually would like the taxon spine to hold actual taxa i.e. including the author name, and not deficient ones without that. 

The problem with 2 is that the taxon name should really be marked as a new taxon including allowing the possibility off adding family name. 

Solution 3 could work if the digitizers are informed of this options and the code filters out the asterisk again. 

So therefore I suggest solution 3.

**Comment by FedorSteeman** [comment] 2024-02-05 14:44
Closing this ticket so the fix can be evaluated. If a different solution is desired, it can be reopened.

**Closed by FedorSteeman** 2024-02-05 14:44 UTC
Labels: bug, UI, found by digitisers

**Comment by jlegind** [comment] 2024-02-07 08:18
- Following the instructions `whenever an end user has a taxon name without author name added, it can escape the matches by adding the asterisk and then pressing escape.` the app is supposed to bypass autosuggest and submit the typed name directly to the taxonomic_name field. This does not happen - instead the taxonomic name field is left blank!

**Comment by FedorSteeman** [comment] 2024-02-07 15:39
Sounds like the wrong version then, as I did change the version number for the release in question. Try again with release v1.1.28.
