### ISSUE TITLE
Hybrids appearing in Digi app exports

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#448] opened 2023-11-03 11:43 UTC
##  What is the issue ?
We have no way of handling hybrid names in the app. They are commented in the remarks field.
Relates to #28

### Detailed description of the issue. 
The names "x cotula" and "x tinctoria" appeared in an export and were noted in the remarks field, for the species Anthemis arvensis.
See attached file :
[NHMD_Herba_20231019_16_26_SS.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/13249686/NHMD_Herba_20231019_16_26_SS.csv)

### Estimate level of effort required.
unknown

### What is the expected acceptable result.
A situation where the hybrids would be available in the app taxonomy for auto suggest.

**Comment by FedorSteeman** [comment] 2023-11-03 13:24
Specify can already handle hybrids. What #28 specifies is how the app db should be adapted to record these so they can readily imported using Workbench.  Since this has not happened, we cannot at the moment import hybrids, though I remember we discussed that we could import these as-is to be fixed after import. Otherwise, it would be better to park these cases. Alternatively, we could adapt the PostProc script to add the necessary columns for import. However, I don't think that's possible, since it needs to be fed the two parent taxa. 

Pip, what do you recall and what would you prefer?

**Comment by FedorSteeman** [comment] 2023-11-03 13:35
Closed as duplicate of #28

**Closed by FedorSteeman** 2023-11-03 13:35 UTC
Labels: specimen data entry, taxonomy, UI
