### ISSUE TITLE
Testing Digi app version 1.1.26

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#478] opened 2024-02-07 08:15 UTC
##  What is the issue ?
- Following the instructions `whenever an end user has a taxon name without author name added, it can escape the matches by adding the asterisk and then pressing escape.` the app is supposed to bypass autosuggest and submit the typed name directly to the taxonomic_name field. This does not happen - instead the taxonomic name field is left blank!

- The title of the Digi app after installation reads Version 1.1.24 while the installation file says "DaSSCoSetup.v1.1.26.exe"
- Though not part of this round of testing: NHMA taxon identifier input crashes the app.

### Estimate level of effort required.
?

###  How to approach it?
Check if the correct app version was compiled and packaged.

**Comment by FedorSteeman** [comment] 2024-02-07 11:09
Duplicate of #476

**Closed by FedorSteeman** 2024-02-07 11:09 UTC
Labels: 1, bug, UI-tested
