### ISSUE TITLE
Validation for eight or nine digit catalog numbers

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#368] opened 2023-08-01 11:27 UTC
##  What is the issue ?
We check catalog numbers for an eight digits catalog number length. The barcode are printed with eight digits. Currently the App has eight digits as a hard requirement.

Right now the App autosaves on eight digit input, yet other collections might have nine digit barcodes.  
 ( **Perhaps even more than that**)

## Estimate level of effort required.

```
# easy to medium
```

## What is the expected acceptable result.

We need to know which catalog number formats can be expected and allow for these to pass a check.

In case there are only two catalog number standards (8 or 9 digits) then the solution would be to test for that range of formats.  
This is the bounded problem.  

Otherwise we could have an ad hoc solution which conforms to the collection in question:
There needs to be an overview of the catalog number formats we can encounter.  
If this is an unbounded problem then we might have to abandon the catalog numbers check.

# What could be the challenges ? 

One of the issues might be that there are many different catalog number formats. 
A large issue is the auto-save feature which activates on 8 digit input. If the input  
is 9 digits this feature would cut off the last digit.
Can we guarantee that it is only digits or can we come across catalog numbers containing text?!

# What test are required ?
Depending on the diversity of catalog number formats, the test suite could become extensive.  
In essence we would need to test for all possible catalog numbers we could encounter. (Problem of unboundedness)

**Comment by FedorSteeman** [comment] 2023-08-04 08:48
Duplicate of #356

**Closed by FedorSteeman** 2023-08-04 08:48 UTC
Labels: duplicate, 1
